import pandas as pd
homelessness = pd.read_csv('homelessness.csv')
print(homelessness)
homelessness.head()
print(homelessness.head())
homelessness.info()
print(homelessness.info())
print(homelessness.shape)
print(homelessness.describe())
print(homelessness.values)
print(homelessness.columns)
print(homelessness.index)
homelessness_ind=homelessness.sort_values("individuals")
print(homelessness_ind.head())
homelessness_fam=homelessness.sort_values("family_members", ascending=False)
print(homelessness_fam.head())
homelessness_reg_fam=homelessness.sort_values(["region", "family_members"], ascending=[True, False])
print(homelessness_reg_fam.head())
individuals=homelessness["individuals"]
print(individuals.head())
